#spring:
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.56.10:3306/GuliStore_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: gulistore-coupon
#
## MapperScan
## sql映射文件位置
#mybatis-plus:
#  mapper-locations: classpath:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#
#server:
#  port: 7000

spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq


        - id: product_route
          uri: lb://gulistore-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: thirdp_route
          uri: lb://gulistore-thirdp
          predicates:
            - Path=/api/thirdp/**
          filters:
            - RewritePath=/api/thirdp/(?<segment>.*),/$\{segment}
#

        - id: member_route
          uri: lb://gulistore-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
#

        - id: ware_route
          uri: lb://gulistore-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
#
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:  # 这段过滤器和验证码有关，api内容缓存了/renren-fast，还得注意/renren-fast也注册到nacos中
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}


        - id: gulistore_host_route
          uri: lb://gulistore-product
          predicates:
            - Host=sukestore.com,item.sukestore.com

        - id: gulistore_search_route
          uri: lb://gulistore-search
          predicates:
            - Host=search.sukestore.com

        - id: gulistore_auth_route
          uri: lb://gulistore-auth-server
          predicates:
            - Host=auth.sukestore.com

        - id: gulistore_cart_route
          uri: lb://gulistore-cart
          predicates:
            - Host=cart.sukestore.com

        - id: gulistore_order_route
          uri: lb://gulistore-order
          predicates:
            - Host=order.sukestore.com

        - id: gulistore_member_route
          uri: lb://gulistore-member
          predicates:
            - Host=member.sukestore.com

        - id: gulistore_seckill_route
          uri: lb://gulistore-seckill
          predicates:
            - Host=seckill.sukestore.com
#         前端项目，/api
#http://localhost:88/api/captcha.jpg              http://localhost:8080/renren-fast/captcha.jpg



## 前端项目，/api前缀。开来到网关后断言先匹配到，过滤器修改url，比如跳转到renren微服务，所以要注意renren后端项目也注册到 nacos里
## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree


